# -*- coding: utf-8 -*-
"""BTP Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IH8TWf4hiApEQ7i2oXB9pkwWhl5aRdsb
"""

import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from PIL import Image
import numpy as np
import os
import matplotlib.pyplot as plt

import zipfile
import os

zip_path = '/content/drive/MyDrive/archive.zip'
extract_path = '/content/extracted_data'

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(f"Zip file extracted to: {extract_path}")

class DeepGlobeDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        # Get a sorted list of image filenames
        self.images = sorted([f for f in os.listdir(image_dir) if f.endswith('_sat.jpg')])

        # --- Create the RGB-to-class_id mapping ---
        #
        self.rgb_to_id = {
            (0, 255, 255): 0,   # urban_land
            (255, 255, 0): 1,   # agriculture_land
            (255, 0, 255): 2,   # rangeland
            (0, 255, 0): 3,     # forest_land
            (0, 0, 255): 4,     # water
            (255, 255, 255): 5, # barren_land
            (0, 0, 0): 6        # unknown
        }

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        # --- 1. Load Files ---
        img_name = self.images[idx]
        mask_name = img_name.replace('_sat.jpg', '_mask.png')

        img_path = os.path.join(self.image_dir, img_name)
        mask_path = os.path.join(self.mask_dir, mask_name)

        # Load as PIL images
        image = Image.open(img_path).convert("RGB")
        mask_rgb = Image.open(mask_path).convert("RGB")

        # Convert to numpy arrays
        image_np = np.array(image)
        mask_rgb_np = np.array(mask_rgb)

        # --- 2. Convert RGB Mask to Integer Mask ---
        # Create an empty mask to fill
        # Note: Use np.int64 for CrossEntropyLoss
        mask_int = np.full((mask_rgb_np.shape[0], mask_rgb_np.shape[1]), fill_value=6, dtype=np.int64)
        for rgb_val, class_id in self.rgb_to_id.items():
            # Find all pixels in the RGB mask that match the current color
            # np.all(..., axis=-1) checks for equality across the last (color) dimension
            target_pixels = np.all(mask_rgb_np == rgb_val, axis=-1)
            # Assign the integer class_id to these pixels in the new mask
            mask_int[target_pixels] = class_id

        # --- 3. Apply Transformations (Augmentations) ---
        # Use a library like 'albumentations' for this
        if self.transform:
            augmented = self.transform(image=image_np, mask=mask_int)
            image_np = augmented['image']
            mask_int = augmented['mask']

        # --- 4. Normalize Image & Convert to Tensors ---
        # Normalize image (simple 0-1 scaling)
        image_tensor = torch.from_numpy(image_np.transpose((2, 0, 1))) / 255.0

        # Convert integer mask to tensor (no division, must be Long type)
        mask_tensor = torch.from_numpy(mask_int).long()

        return image_tensor, mask_tensor

!pip install albumentations

import albumentations as A
from albumentations.pytorch import ToTensorV2

class SimpleTransform:
    def __call__(self, image, mask):
        image = np.array(image)
        mask = np.array(mask)

        # 1. Resize
        # Using PIL for simplicity if albumentations is not installed
        # But A.Resize is better
        img_pil = Image.fromarray(image).resize((256, 256), Image.BILINEAR)
        mask_pil = Image.fromarray(mask).resize((256, 256), Image.NEAREST) # Use NEAREST for masks!

        image = np.array(img_pil)
        mask = np.array(mask_pil)

        # 2. Normalize and Convert to Tensor
        image_tensor = torch.from_numpy(image.transpose((2, 0, 1))) / 255.0
        mask_tensor = torch.from_numpy(mask).long() # .long() is same as torch.int64

        return image_tensor.float(), mask_tensor

# --- 2. Instantiate Dataset and DataLoader ---
# *** UPDATE THESE PATHS to match your Colab structure ***
# (Assuming you unzipped to /content/dataset/)
TRAIN_IMG_DIR = "/content/extracted_data/train"
TRAIN_MASK_DIR = "/content/extracted_data/train"

# Check if paths exist (a good sanity check)
if not os.path.exists(TRAIN_IMG_DIR):
    print(f"ERROR: Path does not exist: {TRAIN_IMG_DIR}")
    print("Please update TRAIN_IMG_DIR to your correct images path.")
else:
    try:
        # We'll use our simple transform for now
        # test_dataset = DeepGlobeDataset(TRAIN_IMG_DIR, TRAIN_MASK_DIR, transform=SimpleTransform())

        # --- A simpler test without transforms, just to check the mask logic ---
        # Let's comment out the transform to test the raw logic first
        print("Testing dataset WITHOUT transforms...")
        test_dataset = DeepGlobeDataset(TRAIN_IMG_DIR, TRAIN_MASK_DIR, transform=None)

        # Use a small batch size for testing
        test_loader = DataLoader(test_dataset, batch_size=4, shuffle=True)

        # --- 3. Get One Batch ---
        print("Fetching one batch from DataLoader...")
        images, masks = next(iter(test_loader))

        # --- 4. Inspect the Output (The "Final Output" Check) ---
        print("\n--- BATCH INSPECTION ---")

        print(f"Images Batch Shape: {images.shape}")
        print(f"Images Batch Dtype: {images.dtype}")
        print(f"Images Min Value:   {images.min()}")
        print(f"Images Max Value:   {images.max()}")

        print("\n" + "-"*20 + "\n")

        print(f"Masks Batch Shape:  {masks.shape}")
        print(f"Masks Batch Dtype:  {masks.dtype}")
        # This is the most important check:
        print(f"Unique values in Masks Batch: {torch.unique(masks)}")

        print("\n--- TEST COMPLETE ---")

    except Exception as e:
        print(f"\nAn error occurred: {e}")
        print("Please check your file paths and the code in your DeepGlobeDataset class.")

try:
    # 1. Get one batch
    images, masks = next(iter(test_loader))

    # 2. Select the first item in the batch (index 0)
    # We need the original mask for comparison. Let's fetch it from the dataset directly.
    # This assumes test_dataset was created without a transform that changes mask size.
    # If using transforms that resize masks, you'd need to load the original mask here.
    # For simplicity, let's assume the dataset returns the original mask or we can access it.
    # A better approach would be to modify the dataset to return the original mask as well.

    # For now, let's just use the integer mask that was processed by the dataset
    # We'll need the original RGB mask to compare against.
    # Let's re-load the original RGB mask for the first image in the batch
    first_image_name = test_dataset.images[0] # Get the filename of the first image
    original_mask_name = first_image_name.replace('_sat.jpg', '_mask.png')
    original_mask_path = os.path.join(test_dataset.mask_dir, original_mask_name)

    original_mask_rgb = Image.open(original_mask_path).convert("RGB")
    original_mask_rgb_np = np.array(original_mask_rgb)

    # The processed mask (integer format) is already in the 'masks' tensor
    processed_mask_np = masks[0].cpu().numpy()


    # 3. Create the side-by-side plot
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))

    # Plot Original RGB Mask
    ax[0].imshow(original_mask_rgb_np)
    ax[0].set_title(f"Original RGB Mask\nShape: {original_mask_rgb_np.shape}")
    ax[0].axis('off') # Hide axes

    # Plot Processed Integer Mask
    # We use a colormap (like 'viridis' or 'tab10') to see the different class IDs
    im = ax[1].imshow(processed_mask_np, cmap='tab10', vmin=0, vmax=6) # vmax=6 (for 7 classes)
    ax[1].set_title(f"Processed Integer Mask\nShape: {processed_mask_np.shape}")
    ax[1].axis('off') # Hide axes

    # Add a color bar to show which color maps to which ID
    fig.colorbar(im, ax=ax[1], ticks=range(7), orientation='vertical')

    plt.tight_layout()
    plt.savefig("mask_comparison.png") # Save the plot
    print("Saved mask comparison plot to mask_comparison.png")

except Exception as e:
    print(f"An error occurred: {e}")
    print("Make sure 'test_loader' and 'test_dataset' were created successfully in the previous cell.")

