import torch
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2
import matplotlib.patches as mpatches


# Import your custom model
from models import SwinUNet

# Import SAM
from segment_anything import sam_model_registry, SamPredictor

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --- PATHS ---
DEEPGLOBE_TEST_IMG = "/home/jayadeepj/Desktop/Urbanlens/data/test/926551_sat.jpg" 
SWIN_CKPT = "checkpoints/Albumented_swin_gpu_gid_latest.pth"
SAM_CKPT = "sam_vit_h_4b8939.pth"

# Let's test on Water (River=13, Lake=14, Pond=15 in GID-15)
TARGET_CLASSES = [13, 14, 15] 

# Same transform used during training
transform = A.Compose([
    A.Resize(224, 224),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

def show_mask(mask, ax, color=np.array([30/255, 144/255, 255/255, 0.6])):
    h, w = mask.shape[-2:]
    mask_image = mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    ax.imshow(mask_image)

def show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0,0,0,0), lw=2))

def run_generalization():
    print("[1] Loading Models...")
    # Load Swin-Unet
    swin = SwinUNet().to(device)
    swin.load_state_dict(torch.load(SWIN_CKPT, map_location=device)["state_dict"])
    swin.eval()

    # Load SAM
    sam = sam_model_registry["vit_h"](checkpoint=SAM_CKPT).to(device)
    sam_predictor = SamPredictor(sam)

    print("[2] Processing DeepGlobe Image...")
    raw_img_pil = Image.open(DEEPGLOBE_TEST_IMG).convert("RGB").resize((224, 224))
    raw_img_np = np.array(raw_img_pil)
    
    # Transform for Swin-Unet
    input_tensor = transform(image=raw_img_np)["image"].unsqueeze(0).to(device)

    print("[3] Swin-Unet Semantic Prediction...")
    with torch.no_grad():
        swin_out = swin(input_tensor)
    
    swin_pred = torch.argmax(swin_out[0], dim=0).cpu().numpy()

    # Create a binary mask of just the target classes (e.g., Water)
    target_mask = np.isin(swin_pred, TARGET_CLASSES).astype(np.uint8)

    # If Swin-Unet found nothing, abort
    if np.sum(target_mask) == 0:
        print("Swin-Unet did not find the target class in this image.")
        return

    print("[4] Extracting Bounding Box for SAM...")
    # Find contours of the predicted water blob to create a bounding box
    contours, _ = cv2.findContours(target_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    # Get the largest blob
    largest_contour = max(contours, key=cv2.contourArea)
    x, y, w, h = cv2.boundingRect(largest_contour)
    input_box = np.array([x, y, x+w, y+h])

    print("[5] SAM Zero-Shot Refinement...")
    # Give SAM the raw image
    sam_predictor.set_image(raw_img_np)
    
    # Give SAM the bounding box generated by Swin-Unet
    masks, _, _ = sam_predictor.predict(
        point_coords=None,
        point_labels=None,
        box=input_box[None, :],
        multimask_output=False,
    )
    sam_mask = masks[0]

    print("[6] Generating Visual Proof...")
    fig, axes = plt.subplots(1, 3, figsize=(22, 7))
    
    # Add a massive main title
    fig.suptitle("Zero-Shot Generalization & Automated Boundary Refinement (DeepGlobe)", 
                 fontsize=22, fontweight='bold', y=1.02)

    # 1. Raw Image
    axes[0].imshow(raw_img_np)
    axes[0].set_title("1. Raw Unlabeled Image", fontsize=16, fontweight='bold', pad=15)
    axes[0].axis('off')

    # 2. Swin-Unet Rough Mask + Bounding Box
    axes[1].imshow(raw_img_np)
    show_mask(target_mask, axes[1], color=np.array([1, 0, 0, 0.5])) # Red mask
    show_box(input_box, axes[1])
    axes[1].set_title("2. Swin-Unet Spatial Intel (Water)", fontsize=16, fontweight='bold', pad=15)
    axes[1].axis('off')

    # 3. SAM Perfect Boundary
    axes[2].imshow(raw_img_np)
    show_mask(sam_mask, axes[2], color=np.array([0, 1, 0, 0.5])) # Green mask
    axes[2].set_title("3. SAM Zero-Shot Refinement", fontsize=16, fontweight='bold', pad=15)
    axes[2].axis('off')

    # --- ADD THE LEGEND ---
    red_patch = mpatches.Patch(color=(1, 0, 0, 0.5), label='Swin-Unet Prediction (Class 13/14/15)')
    green_patch = mpatches.Patch(color=(0, 1, 0, 0.5), label='SAM Pixel-Perfect Boundary')
    box_patch = mpatches.Patch(edgecolor='green', facecolor='none', linewidth=2, label='Swin-Unet Bounding Box Prompt')
    
    fig.legend(handles=[red_patch, box_patch, green_patch], 
               loc="lower center", ncol=3, fontsize=14, bbox_to_anchor=(0.5, -0.05))

    plt.tight_layout()
    plt.savefig("results/DeepGlobe_SAM_Generalization_Presentation.png", dpi=300, bbox_inches='tight')
    plt.close()
    print("Done! Saved to results/DeepGlobe_SAM_Generalization_Presentation.png")

if __name__ == "__main__":
    run_generalization()